#ifndef CAMERASTATUS_IDL_
#define CAMERASTATUS_IDL_
module sensor_msgs {
  struct CameraStatus {
    boolean connected;
    float fps;
    float exposure;
    float gain;
  };
};

#endif  // CAMERASTATUS_IDL_