#include "Header.idl"

module sensor_msgs
{
  struct Image
  {
    std_msgs::Header header;

    uint32 height;
    uint32 width;

    string encoding;

    uint8 is_bigendian;

    uint32 step;

    sequence<octet> data;
  };
};