module jsr {
  module msg {
    /**
     * brief This class represents the structure RpcReqMsg defined by the user in the IDL file.
     */
    struct RpcReqMsg {
      uint64 uuid;
      string header;
      string body;
    };

  };
};
