#include "Image.idl"
#include "CameraInfo.idl"

module sensor_msgs
{
  struct StereoImage
  {
    std_msgs::Header header;
    Image left;
    Image right;
    CameraInfo left_info;
    CameraInfo right_info;
  };
};
