// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Add.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_DEMO_ADD_H_
#define _FAST_DDS_GENERATED_DEMO_ADD_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ADD_SOURCE)
#define ADD_DllAPI __declspec( dllexport )
#else
#define ADD_DllAPI __declspec( dllimport )
#endif // ADD_SOURCE
#else
#define ADD_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ADD_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace demo {



/*!
 * @brief This class represents the structure AddRequest defined by the user in the IDL file.
 * @ingroup Add
 */
class AddRequest : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef AddRequest type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API AddRequest();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~AddRequest() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object demo::AddRequest that will be copied.
     */
    FASTDDS_EXPORTED_API AddRequest(
            const AddRequest& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object demo::AddRequest that will be copied.
     */
    FASTDDS_EXPORTED_API AddRequest(
            AddRequest&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object demo::AddRequest that will be copied.
     */
    FASTDDS_EXPORTED_API AddRequest& operator =(
            const AddRequest& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object demo::AddRequest that will be copied.
     */
    FASTDDS_EXPORTED_API AddRequest& operator =(
            AddRequest&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x demo::AddRequest object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const AddRequest& x) const;

    /*!
     * @brief Comparison operator.
     * @param x demo::AddRequest object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const AddRequest& x) const;

    /*!
     * @brief This function sets a value in member a
     * @param _a New value for member a
     */
    FASTDDS_EXPORTED_API void a(
            int32_t _a);

    /*!
     * @brief This function returns the value of member a
     * @return Value of member a
     */
    FASTDDS_EXPORTED_API int32_t a() const;

    /*!
     * @brief This function returns a reference to member a
     * @return Reference to member a
     */
    FASTDDS_EXPORTED_API int32_t& a();


    /*!
     * @brief This function sets a value in member b
     * @param _b New value for member b
     */
    FASTDDS_EXPORTED_API void b(
            int32_t _b);

    /*!
     * @brief This function returns the value of member b
     * @return Value of member b
     */
    FASTDDS_EXPORTED_API int32_t b() const;

    /*!
     * @brief This function returns a reference to member b
     * @return Reference to member b
     */
    FASTDDS_EXPORTED_API int32_t& b();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    int32_t m_a{0};
    int32_t m_b{0};

};


/*!
 * @brief This class represents the structure AddReply defined by the user in the IDL file.
 * @ingroup Add
 */
class AddReply : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef AddReply type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API AddReply();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~AddReply() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object demo::AddReply that will be copied.
     */
    FASTDDS_EXPORTED_API AddReply(
            const AddReply& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object demo::AddReply that will be copied.
     */
    FASTDDS_EXPORTED_API AddReply(
            AddReply&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object demo::AddReply that will be copied.
     */
    FASTDDS_EXPORTED_API AddReply& operator =(
            const AddReply& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object demo::AddReply that will be copied.
     */
    FASTDDS_EXPORTED_API AddReply& operator =(
            AddReply&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x demo::AddReply object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const AddReply& x) const;

    /*!
     * @brief Comparison operator.
     * @param x demo::AddReply object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const AddReply& x) const;

    /*!
     * @brief This function sets a value in member sum
     * @param _sum New value for member sum
     */
    FASTDDS_EXPORTED_API void sum(
            int32_t _sum);

    /*!
     * @brief This function returns the value of member sum
     * @return Value of member sum
     */
    FASTDDS_EXPORTED_API int32_t sum() const;

    /*!
     * @brief This function returns a reference to member sum
     * @return Reference to member sum
     */
    FASTDDS_EXPORTED_API int32_t& sum();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    int32_t m_sum{0};

};
/*!
 * @brief This class represents the interface Add defined by the user in the IDL file.
 * @ingroup Add
 */
class ADD_DllAPI Add 
{
public:



};

} // namespace demo

#endif // _FAST_DDS_GENERATED_DEMO_ADD_H_



