// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CameraStatus.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_CAMERASTATUS_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_CAMERASTATUS_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CAMERASTATUS_SOURCE)
#define CAMERASTATUS_DllAPI __declspec( dllexport )
#else
#define CAMERASTATUS_DllAPI __declspec( dllimport )
#endif // CAMERASTATUS_SOURCE
#else
#define CAMERASTATUS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CAMERASTATUS_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace sensor_msgs {



/*!
 * @brief This class represents the structure CameraStatus defined by the user in the IDL file.
 * @ingroup CameraStatus
 */
class CameraStatus : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef CameraStatus type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API CameraStatus();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~CameraStatus() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object sensor_msgs::CameraStatus that will be copied.
     */
    FASTDDS_EXPORTED_API CameraStatus(
            const CameraStatus& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object sensor_msgs::CameraStatus that will be copied.
     */
    FASTDDS_EXPORTED_API CameraStatus(
            CameraStatus&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object sensor_msgs::CameraStatus that will be copied.
     */
    FASTDDS_EXPORTED_API CameraStatus& operator =(
            const CameraStatus& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object sensor_msgs::CameraStatus that will be copied.
     */
    FASTDDS_EXPORTED_API CameraStatus& operator =(
            CameraStatus&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::CameraStatus object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const CameraStatus& x) const;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::CameraStatus object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const CameraStatus& x) const;

    /*!
     * @brief This function sets a value in member connected
     * @param _connected New value for member connected
     */
    FASTDDS_EXPORTED_API void connected(
            bool _connected);

    /*!
     * @brief This function returns the value of member connected
     * @return Value of member connected
     */
    FASTDDS_EXPORTED_API bool connected() const;

    /*!
     * @brief This function returns a reference to member connected
     * @return Reference to member connected
     */
    FASTDDS_EXPORTED_API bool& connected();


    /*!
     * @brief This function sets a value in member fps
     * @param _fps New value for member fps
     */
    FASTDDS_EXPORTED_API void fps(
            float _fps);

    /*!
     * @brief This function returns the value of member fps
     * @return Value of member fps
     */
    FASTDDS_EXPORTED_API float fps() const;

    /*!
     * @brief This function returns a reference to member fps
     * @return Reference to member fps
     */
    FASTDDS_EXPORTED_API float& fps();


    /*!
     * @brief This function sets a value in member exposure
     * @param _exposure New value for member exposure
     */
    FASTDDS_EXPORTED_API void exposure(
            float _exposure);

    /*!
     * @brief This function returns the value of member exposure
     * @return Value of member exposure
     */
    FASTDDS_EXPORTED_API float exposure() const;

    /*!
     * @brief This function returns a reference to member exposure
     * @return Reference to member exposure
     */
    FASTDDS_EXPORTED_API float& exposure();


    /*!
     * @brief This function sets a value in member gain
     * @param _gain New value for member gain
     */
    FASTDDS_EXPORTED_API void gain(
            float _gain);

    /*!
     * @brief This function returns the value of member gain
     * @return Value of member gain
     */
    FASTDDS_EXPORTED_API float gain() const;

    /*!
     * @brief This function returns a reference to member gain
     * @return Reference to member gain
     */
    FASTDDS_EXPORTED_API float& gain();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    bool m_connected{false};
    float m_fps{0.0};
    float m_exposure{0.0};
    float m_gain{0.0};

};

} // namespace sensor_msgs

#endif // _FAST_DDS_GENERATED_SENSOR_MSGS_CAMERASTATUS_H_



