// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ColorRGBA.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_STD_MSGS_MSG_COLORRGBA_H_
#define _FAST_DDS_GENERATED_STD_MSGS_MSG_COLORRGBA_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(COLORRGBA_SOURCE)
#define COLORRGBA_DllAPI __declspec( dllexport )
#else
#define COLORRGBA_DllAPI __declspec( dllimport )
#endif // COLORRGBA_SOURCE
#else
#define COLORRGBA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define COLORRGBA_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace std_msgs {

namespace msg {



/*!
 * @brief This class represents the structure ColorRGBA defined by the user in the IDL file.
 * @ingroup ColorRGBA
 */
class ColorRGBA : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef ColorRGBA type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API ColorRGBA();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~ColorRGBA() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object std_msgs::msg::ColorRGBA that will be copied.
     */
    FASTDDS_EXPORTED_API ColorRGBA(
            const ColorRGBA& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object std_msgs::msg::ColorRGBA that will be copied.
     */
    FASTDDS_EXPORTED_API ColorRGBA(
            ColorRGBA&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object std_msgs::msg::ColorRGBA that will be copied.
     */
    FASTDDS_EXPORTED_API ColorRGBA& operator =(
            const ColorRGBA& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object std_msgs::msg::ColorRGBA that will be copied.
     */
    FASTDDS_EXPORTED_API ColorRGBA& operator =(
            ColorRGBA&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x std_msgs::msg::ColorRGBA object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const ColorRGBA& x) const;

    /*!
     * @brief Comparison operator.
     * @param x std_msgs::msg::ColorRGBA object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const ColorRGBA& x) const;

    /*!
     * @brief This function sets a value in member r
     * @param _r New value for member r
     */
    FASTDDS_EXPORTED_API void r(
            float _r);

    /*!
     * @brief This function returns the value of member r
     * @return Value of member r
     */
    FASTDDS_EXPORTED_API float r() const;

    /*!
     * @brief This function returns a reference to member r
     * @return Reference to member r
     */
    FASTDDS_EXPORTED_API float& r();


    /*!
     * @brief This function sets a value in member g
     * @param _g New value for member g
     */
    FASTDDS_EXPORTED_API void g(
            float _g);

    /*!
     * @brief This function returns the value of member g
     * @return Value of member g
     */
    FASTDDS_EXPORTED_API float g() const;

    /*!
     * @brief This function returns a reference to member g
     * @return Reference to member g
     */
    FASTDDS_EXPORTED_API float& g();


    /*!
     * @brief This function sets a value in member b
     * @param _b New value for member b
     */
    FASTDDS_EXPORTED_API void b(
            float _b);

    /*!
     * @brief This function returns the value of member b
     * @return Value of member b
     */
    FASTDDS_EXPORTED_API float b() const;

    /*!
     * @brief This function returns a reference to member b
     * @return Reference to member b
     */
    FASTDDS_EXPORTED_API float& b();


    /*!
     * @brief This function sets a value in member a
     * @param _a New value for member a
     */
    FASTDDS_EXPORTED_API void a(
            float _a);

    /*!
     * @brief This function returns the value of member a
     * @return Value of member a
     */
    FASTDDS_EXPORTED_API float a() const;

    /*!
     * @brief This function returns a reference to member a
     * @return Reference to member a
     */
    FASTDDS_EXPORTED_API float& a();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    float m_r{0.0};
    float m_g{0.0};
    float m_b{0.0};
    float m_a{0.0};

};

} // namespace msg

} // namespace std_msgs

#endif // _FAST_DDS_GENERATED_STD_MSGS_MSG_COLORRGBA_H_



