// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DiagnosticStatus.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_DIAGNOSTIC_MSGS_MSG_DIAGNOSTICSTATUS_H_
#define _FAST_DDS_GENERATED_DIAGNOSTIC_MSGS_MSG_DIAGNOSTICSTATUS_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "KeyValue.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DIAGNOSTICSTATUS_SOURCE)
#define DIAGNOSTICSTATUS_DllAPI __declspec( dllexport )
#else
#define DIAGNOSTICSTATUS_DllAPI __declspec( dllimport )
#endif // DIAGNOSTICSTATUS_SOURCE
#else
#define DIAGNOSTICSTATUS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DIAGNOSTICSTATUS_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace diagnostic_msgs {

namespace msg {

namespace DiagnosticStatus_Constants {

const uint8_t OK = 0;
const uint8_t WARN = 1;
const uint8_t ERROR = 2;
const uint8_t STALE = 3;

} // namespace DiagnosticStatus_Constants




/*!
 * @brief This class represents the structure DiagnosticStatus defined by the user in the IDL file.
 * @ingroup DiagnosticStatus
 */
class DiagnosticStatus : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef DiagnosticStatus type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API DiagnosticStatus();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~DiagnosticStatus() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object diagnostic_msgs::msg::DiagnosticStatus that will be copied.
     */
    FASTDDS_EXPORTED_API DiagnosticStatus(
            const DiagnosticStatus& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object diagnostic_msgs::msg::DiagnosticStatus that will be copied.
     */
    FASTDDS_EXPORTED_API DiagnosticStatus(
            DiagnosticStatus&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object diagnostic_msgs::msg::DiagnosticStatus that will be copied.
     */
    FASTDDS_EXPORTED_API DiagnosticStatus& operator =(
            const DiagnosticStatus& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object diagnostic_msgs::msg::DiagnosticStatus that will be copied.
     */
    FASTDDS_EXPORTED_API DiagnosticStatus& operator =(
            DiagnosticStatus&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x diagnostic_msgs::msg::DiagnosticStatus object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const DiagnosticStatus& x) const;

    /*!
     * @brief Comparison operator.
     * @param x diagnostic_msgs::msg::DiagnosticStatus object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const DiagnosticStatus& x) const;

    /*!
     * @brief This function sets a value in member level
     * @param _level New value for member level
     */
    FASTDDS_EXPORTED_API void level(
            uint8_t _level);

    /*!
     * @brief This function returns the value of member level
     * @return Value of member level
     */
    FASTDDS_EXPORTED_API uint8_t level() const;

    /*!
     * @brief This function returns a reference to member level
     * @return Reference to member level
     */
    FASTDDS_EXPORTED_API uint8_t& level();


    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    FASTDDS_EXPORTED_API void name(
            const std::string& _name);

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    FASTDDS_EXPORTED_API void name(
            std::string&& _name);

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    FASTDDS_EXPORTED_API const std::string& name() const;

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    FASTDDS_EXPORTED_API std::string& name();


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    FASTDDS_EXPORTED_API void message(
            const std::string& _message);

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    FASTDDS_EXPORTED_API void message(
            std::string&& _message);

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    FASTDDS_EXPORTED_API const std::string& message() const;

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    FASTDDS_EXPORTED_API std::string& message();


    /*!
     * @brief This function copies the value in member hardware_id
     * @param _hardware_id New value to be copied in member hardware_id
     */
    FASTDDS_EXPORTED_API void hardware_id(
            const std::string& _hardware_id);

    /*!
     * @brief This function moves the value in member hardware_id
     * @param _hardware_id New value to be moved in member hardware_id
     */
    FASTDDS_EXPORTED_API void hardware_id(
            std::string&& _hardware_id);

    /*!
     * @brief This function returns a constant reference to member hardware_id
     * @return Constant reference to member hardware_id
     */
    FASTDDS_EXPORTED_API const std::string& hardware_id() const;

    /*!
     * @brief This function returns a reference to member hardware_id
     * @return Reference to member hardware_id
     */
    FASTDDS_EXPORTED_API std::string& hardware_id();


    /*!
     * @brief This function copies the value in member values
     * @param _values New value to be copied in member values
     */
    FASTDDS_EXPORTED_API void values(
            const std::vector<diagnostic_msgs::msg::KeyValue>& _values);

    /*!
     * @brief This function moves the value in member values
     * @param _values New value to be moved in member values
     */
    FASTDDS_EXPORTED_API void values(
            std::vector<diagnostic_msgs::msg::KeyValue>&& _values);

    /*!
     * @brief This function returns a constant reference to member values
     * @return Constant reference to member values
     */
    FASTDDS_EXPORTED_API const std::vector<diagnostic_msgs::msg::KeyValue>& values() const;

    /*!
     * @brief This function returns a reference to member values
     * @return Reference to member values
     */
    FASTDDS_EXPORTED_API std::vector<diagnostic_msgs::msg::KeyValue>& values();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    uint8_t m_level{0};
    std::string m_name;
    std::string m_message;
    std::string m_hardware_id;
    std::vector<diagnostic_msgs::msg::KeyValue> m_values;

};

} // namespace msg

} // namespace diagnostic_msgs

#endif // _FAST_DDS_GENERATED_DIAGNOSTIC_MSGS_MSG_DIAGNOSTICSTATUS_H_



