// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Float64MultiArray.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_STD_MSGS_MSG_FLOAT64MULTIARRAY_H_
#define _FAST_DDS_GENERATED_STD_MSGS_MSG_FLOAT64MULTIARRAY_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "MultiArrayLayout.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(FLOAT64MULTIARRAY_SOURCE)
#define FLOAT64MULTIARRAY_DllAPI __declspec( dllexport )
#else
#define FLOAT64MULTIARRAY_DllAPI __declspec( dllimport )
#endif // FLOAT64MULTIARRAY_SOURCE
#else
#define FLOAT64MULTIARRAY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FLOAT64MULTIARRAY_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace std_msgs {

namespace msg {





/*!
 * @brief This class represents the structure Float64MultiArray defined by the user in the IDL file.
 * @ingroup Float64MultiArray
 */
class Float64MultiArray : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef Float64MultiArray type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API Float64MultiArray();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~Float64MultiArray() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object std_msgs::msg::Float64MultiArray that will be copied.
     */
    FASTDDS_EXPORTED_API Float64MultiArray(
            const Float64MultiArray& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object std_msgs::msg::Float64MultiArray that will be copied.
     */
    FASTDDS_EXPORTED_API Float64MultiArray(
            Float64MultiArray&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object std_msgs::msg::Float64MultiArray that will be copied.
     */
    FASTDDS_EXPORTED_API Float64MultiArray& operator =(
            const Float64MultiArray& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object std_msgs::msg::Float64MultiArray that will be copied.
     */
    FASTDDS_EXPORTED_API Float64MultiArray& operator =(
            Float64MultiArray&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x std_msgs::msg::Float64MultiArray object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const Float64MultiArray& x) const;

    /*!
     * @brief Comparison operator.
     * @param x std_msgs::msg::Float64MultiArray object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const Float64MultiArray& x) const;

    /*!
     * @brief This function copies the value in member layout
     * @param _layout New value to be copied in member layout
     */
    FASTDDS_EXPORTED_API void layout(
            const std_msgs::msg::MultiArrayLayout& _layout);

    /*!
     * @brief This function moves the value in member layout
     * @param _layout New value to be moved in member layout
     */
    FASTDDS_EXPORTED_API void layout(
            std_msgs::msg::MultiArrayLayout&& _layout);

    /*!
     * @brief This function returns a constant reference to member layout
     * @return Constant reference to member layout
     */
    FASTDDS_EXPORTED_API const std_msgs::msg::MultiArrayLayout& layout() const;

    /*!
     * @brief This function returns a reference to member layout
     * @return Reference to member layout
     */
    FASTDDS_EXPORTED_API std_msgs::msg::MultiArrayLayout& layout();


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    FASTDDS_EXPORTED_API void data(
            const std::vector<double>& _data);

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    FASTDDS_EXPORTED_API void data(
            std::vector<double>&& _data);

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    FASTDDS_EXPORTED_API const std::vector<double>& data() const;

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    FASTDDS_EXPORTED_API std::vector<double>& data();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    std_msgs::msg::MultiArrayLayout m_layout;
    std::vector<double> m_data;

};

} // namespace msg

} // namespace std_msgs

#endif // _FAST_DDS_GENERATED_STD_MSGS_MSG_FLOAT64MULTIARRAY_H_



