// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ImuState.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_JSR_MSG_IMUSTATE_H_
#define _FAST_DDS_GENERATED_JSR_MSG_IMUSTATE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(IMUSTATE_SOURCE)
#define IMUSTATE_DllAPI __declspec( dllexport )
#else
#define IMUSTATE_DllAPI __declspec( dllimport )
#endif // IMUSTATE_SOURCE
#else
#define IMUSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define IMUSTATE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace jsr {

namespace msg {



/*!
 * @brief This class represents the structure ImuState defined by the user in the IDL file.
 * @ingroup ImuState
 */
class ImuState : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef ImuState type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API ImuState();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~ImuState() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object jsr::msg::ImuState that will be copied.
     */
    FASTDDS_EXPORTED_API ImuState(
            const ImuState& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object jsr::msg::ImuState that will be copied.
     */
    FASTDDS_EXPORTED_API ImuState(
            ImuState&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object jsr::msg::ImuState that will be copied.
     */
    FASTDDS_EXPORTED_API ImuState& operator =(
            const ImuState& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object jsr::msg::ImuState that will be copied.
     */
    FASTDDS_EXPORTED_API ImuState& operator =(
            ImuState&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::ImuState object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const ImuState& x) const;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::ImuState object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const ImuState& x) const;

    /*!
     * @brief This function copies the value in member rpy
     * @param _rpy New value to be copied in member rpy
     */
    FASTDDS_EXPORTED_API void rpy(
            const std::array<float, 3>& _rpy);

    /*!
     * @brief This function moves the value in member rpy
     * @param _rpy New value to be moved in member rpy
     */
    FASTDDS_EXPORTED_API void rpy(
            std::array<float, 3>&& _rpy);

    /*!
     * @brief This function returns a constant reference to member rpy
     * @return Constant reference to member rpy
     */
    FASTDDS_EXPORTED_API const std::array<float, 3>& rpy() const;

    /*!
     * @brief This function returns a reference to member rpy
     * @return Reference to member rpy
     */
    FASTDDS_EXPORTED_API std::array<float, 3>& rpy();


    /*!
     * @brief This function copies the value in member gyro
     * @param _gyro New value to be copied in member gyro
     */
    FASTDDS_EXPORTED_API void gyro(
            const std::array<float, 3>& _gyro);

    /*!
     * @brief This function moves the value in member gyro
     * @param _gyro New value to be moved in member gyro
     */
    FASTDDS_EXPORTED_API void gyro(
            std::array<float, 3>&& _gyro);

    /*!
     * @brief This function returns a constant reference to member gyro
     * @return Constant reference to member gyro
     */
    FASTDDS_EXPORTED_API const std::array<float, 3>& gyro() const;

    /*!
     * @brief This function returns a reference to member gyro
     * @return Reference to member gyro
     */
    FASTDDS_EXPORTED_API std::array<float, 3>& gyro();


    /*!
     * @brief This function copies the value in member acc
     * @param _acc New value to be copied in member acc
     */
    FASTDDS_EXPORTED_API void acc(
            const std::array<float, 3>& _acc);

    /*!
     * @brief This function moves the value in member acc
     * @param _acc New value to be moved in member acc
     */
    FASTDDS_EXPORTED_API void acc(
            std::array<float, 3>&& _acc);

    /*!
     * @brief This function returns a constant reference to member acc
     * @return Constant reference to member acc
     */
    FASTDDS_EXPORTED_API const std::array<float, 3>& acc() const;

    /*!
     * @brief This function returns a reference to member acc
     * @return Reference to member acc
     */
    FASTDDS_EXPORTED_API std::array<float, 3>& acc();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    std::array<float, 3> m_rpy{0.0};
    std::array<float, 3> m_gyro{0.0};
    std::array<float, 3> m_acc{0.0};

};

} // namespace msg

} // namespace jsr

#endif // _FAST_DDS_GENERATED_JSR_MSG_IMUSTATE_H_



