// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Inertia.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_INERTIA_H_
#define _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_INERTIA_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "Vector3.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(INERTIA_SOURCE)
#define INERTIA_DllAPI __declspec( dllexport )
#else
#define INERTIA_DllAPI __declspec( dllimport )
#endif // INERTIA_SOURCE
#else
#define INERTIA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define INERTIA_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace geometry_msgs {

namespace msg {



/*!
 * @brief This class represents the structure Inertia defined by the user in the IDL file.
 * @ingroup Inertia
 */
class Inertia : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef Inertia type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API Inertia();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~Inertia() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object geometry_msgs::msg::Inertia that will be copied.
     */
    FASTDDS_EXPORTED_API Inertia(
            const Inertia& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object geometry_msgs::msg::Inertia that will be copied.
     */
    FASTDDS_EXPORTED_API Inertia(
            Inertia&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object geometry_msgs::msg::Inertia that will be copied.
     */
    FASTDDS_EXPORTED_API Inertia& operator =(
            const Inertia& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object geometry_msgs::msg::Inertia that will be copied.
     */
    FASTDDS_EXPORTED_API Inertia& operator =(
            Inertia&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x geometry_msgs::msg::Inertia object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const Inertia& x) const;

    /*!
     * @brief Comparison operator.
     * @param x geometry_msgs::msg::Inertia object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const Inertia& x) const;

    /*!
     * @brief This function sets a value in member m
     * @param _m New value for member m
     */
    FASTDDS_EXPORTED_API void m(
            double _m);

    /*!
     * @brief This function returns the value of member m
     * @return Value of member m
     */
    FASTDDS_EXPORTED_API double m() const;

    /*!
     * @brief This function returns a reference to member m
     * @return Reference to member m
     */
    FASTDDS_EXPORTED_API double& m();


    /*!
     * @brief This function copies the value in member com
     * @param _com New value to be copied in member com
     */
    FASTDDS_EXPORTED_API void com(
            const geometry_msgs::msg::Vector3& _com);

    /*!
     * @brief This function moves the value in member com
     * @param _com New value to be moved in member com
     */
    FASTDDS_EXPORTED_API void com(
            geometry_msgs::msg::Vector3&& _com);

    /*!
     * @brief This function returns a constant reference to member com
     * @return Constant reference to member com
     */
    FASTDDS_EXPORTED_API const geometry_msgs::msg::Vector3& com() const;

    /*!
     * @brief This function returns a reference to member com
     * @return Reference to member com
     */
    FASTDDS_EXPORTED_API geometry_msgs::msg::Vector3& com();


    /*!
     * @brief This function sets a value in member ixx
     * @param _ixx New value for member ixx
     */
    FASTDDS_EXPORTED_API void ixx(
            double _ixx);

    /*!
     * @brief This function returns the value of member ixx
     * @return Value of member ixx
     */
    FASTDDS_EXPORTED_API double ixx() const;

    /*!
     * @brief This function returns a reference to member ixx
     * @return Reference to member ixx
     */
    FASTDDS_EXPORTED_API double& ixx();


    /*!
     * @brief This function sets a value in member ixy
     * @param _ixy New value for member ixy
     */
    FASTDDS_EXPORTED_API void ixy(
            double _ixy);

    /*!
     * @brief This function returns the value of member ixy
     * @return Value of member ixy
     */
    FASTDDS_EXPORTED_API double ixy() const;

    /*!
     * @brief This function returns a reference to member ixy
     * @return Reference to member ixy
     */
    FASTDDS_EXPORTED_API double& ixy();


    /*!
     * @brief This function sets a value in member ixz
     * @param _ixz New value for member ixz
     */
    FASTDDS_EXPORTED_API void ixz(
            double _ixz);

    /*!
     * @brief This function returns the value of member ixz
     * @return Value of member ixz
     */
    FASTDDS_EXPORTED_API double ixz() const;

    /*!
     * @brief This function returns a reference to member ixz
     * @return Reference to member ixz
     */
    FASTDDS_EXPORTED_API double& ixz();


    /*!
     * @brief This function sets a value in member iyy
     * @param _iyy New value for member iyy
     */
    FASTDDS_EXPORTED_API void iyy(
            double _iyy);

    /*!
     * @brief This function returns the value of member iyy
     * @return Value of member iyy
     */
    FASTDDS_EXPORTED_API double iyy() const;

    /*!
     * @brief This function returns a reference to member iyy
     * @return Reference to member iyy
     */
    FASTDDS_EXPORTED_API double& iyy();


    /*!
     * @brief This function sets a value in member iyz
     * @param _iyz New value for member iyz
     */
    FASTDDS_EXPORTED_API void iyz(
            double _iyz);

    /*!
     * @brief This function returns the value of member iyz
     * @return Value of member iyz
     */
    FASTDDS_EXPORTED_API double iyz() const;

    /*!
     * @brief This function returns a reference to member iyz
     * @return Reference to member iyz
     */
    FASTDDS_EXPORTED_API double& iyz();


    /*!
     * @brief This function sets a value in member izz
     * @param _izz New value for member izz
     */
    FASTDDS_EXPORTED_API void izz(
            double _izz);

    /*!
     * @brief This function returns the value of member izz
     * @return Value of member izz
     */
    FASTDDS_EXPORTED_API double izz() const;

    /*!
     * @brief This function returns a reference to member izz
     * @return Reference to member izz
     */
    FASTDDS_EXPORTED_API double& izz();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    double m_m{0.0};
    geometry_msgs::msg::Vector3 m_com;
    double m_ixx{0.0};
    double m_ixy{0.0};
    double m_ixz{0.0};
    double m_iyy{0.0};
    double m_iyz{0.0};
    double m_izz{0.0};

};

} // namespace msg

} // namespace geometry_msgs

#endif // _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_INERTIA_H_



