// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file JointTrajectory.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_TRAJECTORY_MSGS_MSG_JOINTTRAJECTORY_H_
#define _FAST_DDS_GENERATED_TRAJECTORY_MSGS_MSG_JOINTTRAJECTORY_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "JointTrajectoryPoint.hpp"
#include "Header.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(JOINTTRAJECTORY_SOURCE)
#define JOINTTRAJECTORY_DllAPI __declspec( dllexport )
#else
#define JOINTTRAJECTORY_DllAPI __declspec( dllimport )
#endif // JOINTTRAJECTORY_SOURCE
#else
#define JOINTTRAJECTORY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define JOINTTRAJECTORY_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace trajectory_msgs {

namespace msg {





/*!
 * @brief This class represents the structure JointTrajectory defined by the user in the IDL file.
 * @ingroup JointTrajectory
 */
class JointTrajectory : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef JointTrajectory type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API JointTrajectory();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~JointTrajectory() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object trajectory_msgs::msg::JointTrajectory that will be copied.
     */
    FASTDDS_EXPORTED_API JointTrajectory(
            const JointTrajectory& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object trajectory_msgs::msg::JointTrajectory that will be copied.
     */
    FASTDDS_EXPORTED_API JointTrajectory(
            JointTrajectory&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object trajectory_msgs::msg::JointTrajectory that will be copied.
     */
    FASTDDS_EXPORTED_API JointTrajectory& operator =(
            const JointTrajectory& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object trajectory_msgs::msg::JointTrajectory that will be copied.
     */
    FASTDDS_EXPORTED_API JointTrajectory& operator =(
            JointTrajectory&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x trajectory_msgs::msg::JointTrajectory object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const JointTrajectory& x) const;

    /*!
     * @brief Comparison operator.
     * @param x trajectory_msgs::msg::JointTrajectory object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const JointTrajectory& x) const;

    /*!
     * @brief This function copies the value in member header_
     * @param _header_ New value to be copied in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            const std_msgs::msg::Header& _header_);

    /*!
     * @brief This function moves the value in member header_
     * @param _header_ New value to be moved in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            std_msgs::msg::Header&& _header_);

    /*!
     * @brief This function returns a constant reference to member header_
     * @return Constant reference to member header_
     */
    FASTDDS_EXPORTED_API const std_msgs::msg::Header& header_() const;

    /*!
     * @brief This function returns a reference to member header_
     * @return Reference to member header_
     */
    FASTDDS_EXPORTED_API std_msgs::msg::Header& header_();


    /*!
     * @brief This function copies the value in member joint_names
     * @param _joint_names New value to be copied in member joint_names
     */
    FASTDDS_EXPORTED_API void joint_names(
            const std::vector<std::string>& _joint_names);

    /*!
     * @brief This function moves the value in member joint_names
     * @param _joint_names New value to be moved in member joint_names
     */
    FASTDDS_EXPORTED_API void joint_names(
            std::vector<std::string>&& _joint_names);

    /*!
     * @brief This function returns a constant reference to member joint_names
     * @return Constant reference to member joint_names
     */
    FASTDDS_EXPORTED_API const std::vector<std::string>& joint_names() const;

    /*!
     * @brief This function returns a reference to member joint_names
     * @return Reference to member joint_names
     */
    FASTDDS_EXPORTED_API std::vector<std::string>& joint_names();


    /*!
     * @brief This function copies the value in member points
     * @param _points New value to be copied in member points
     */
    FASTDDS_EXPORTED_API void points(
            const std::vector<trajectory_msgs::msg::JointTrajectoryPoint>& _points);

    /*!
     * @brief This function moves the value in member points
     * @param _points New value to be moved in member points
     */
    FASTDDS_EXPORTED_API void points(
            std::vector<trajectory_msgs::msg::JointTrajectoryPoint>&& _points);

    /*!
     * @brief This function returns a constant reference to member points
     * @return Constant reference to member points
     */
    FASTDDS_EXPORTED_API const std::vector<trajectory_msgs::msg::JointTrajectoryPoint>& points() const;

    /*!
     * @brief This function returns a reference to member points
     * @return Reference to member points
     */
    FASTDDS_EXPORTED_API std::vector<trajectory_msgs::msg::JointTrajectoryPoint>& points();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    std_msgs::msg::Header m_header_;
    std::vector<std::string> m_joint_names;
    std::vector<trajectory_msgs::msg::JointTrajectoryPoint> m_points;

};

} // namespace msg

} // namespace trajectory_msgs

#endif // _FAST_DDS_GENERATED_TRAJECTORY_MSGS_MSG_JOINTTRAJECTORY_H_



