// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file JointTrajectoryPoint.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_TRAJECTORY_MSGS_MSG_JOINTTRAJECTORYPOINT_H_
#define _FAST_DDS_GENERATED_TRAJECTORY_MSGS_MSG_JOINTTRAJECTORYPOINT_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "Duration.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(JOINTTRAJECTORYPOINT_SOURCE)
#define JOINTTRAJECTORYPOINT_DllAPI __declspec( dllexport )
#else
#define JOINTTRAJECTORYPOINT_DllAPI __declspec( dllimport )
#endif // JOINTTRAJECTORYPOINT_SOURCE
#else
#define JOINTTRAJECTORYPOINT_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define JOINTTRAJECTORYPOINT_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace trajectory_msgs {

namespace msg {



/*!
 * @brief This class represents the structure JointTrajectoryPoint defined by the user in the IDL file.
 * @ingroup JointTrajectoryPoint
 */
class JointTrajectoryPoint : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef JointTrajectoryPoint type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API JointTrajectoryPoint();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~JointTrajectoryPoint() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object trajectory_msgs::msg::JointTrajectoryPoint that will be copied.
     */
    FASTDDS_EXPORTED_API JointTrajectoryPoint(
            const JointTrajectoryPoint& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object trajectory_msgs::msg::JointTrajectoryPoint that will be copied.
     */
    FASTDDS_EXPORTED_API JointTrajectoryPoint(
            JointTrajectoryPoint&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object trajectory_msgs::msg::JointTrajectoryPoint that will be copied.
     */
    FASTDDS_EXPORTED_API JointTrajectoryPoint& operator =(
            const JointTrajectoryPoint& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object trajectory_msgs::msg::JointTrajectoryPoint that will be copied.
     */
    FASTDDS_EXPORTED_API JointTrajectoryPoint& operator =(
            JointTrajectoryPoint&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x trajectory_msgs::msg::JointTrajectoryPoint object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const JointTrajectoryPoint& x) const;

    /*!
     * @brief Comparison operator.
     * @param x trajectory_msgs::msg::JointTrajectoryPoint object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const JointTrajectoryPoint& x) const;

    /*!
     * @brief This function copies the value in member positions
     * @param _positions New value to be copied in member positions
     */
    FASTDDS_EXPORTED_API void positions(
            const std::vector<double>& _positions);

    /*!
     * @brief This function moves the value in member positions
     * @param _positions New value to be moved in member positions
     */
    FASTDDS_EXPORTED_API void positions(
            std::vector<double>&& _positions);

    /*!
     * @brief This function returns a constant reference to member positions
     * @return Constant reference to member positions
     */
    FASTDDS_EXPORTED_API const std::vector<double>& positions() const;

    /*!
     * @brief This function returns a reference to member positions
     * @return Reference to member positions
     */
    FASTDDS_EXPORTED_API std::vector<double>& positions();


    /*!
     * @brief This function copies the value in member velocities
     * @param _velocities New value to be copied in member velocities
     */
    FASTDDS_EXPORTED_API void velocities(
            const std::vector<double>& _velocities);

    /*!
     * @brief This function moves the value in member velocities
     * @param _velocities New value to be moved in member velocities
     */
    FASTDDS_EXPORTED_API void velocities(
            std::vector<double>&& _velocities);

    /*!
     * @brief This function returns a constant reference to member velocities
     * @return Constant reference to member velocities
     */
    FASTDDS_EXPORTED_API const std::vector<double>& velocities() const;

    /*!
     * @brief This function returns a reference to member velocities
     * @return Reference to member velocities
     */
    FASTDDS_EXPORTED_API std::vector<double>& velocities();


    /*!
     * @brief This function copies the value in member accelerations
     * @param _accelerations New value to be copied in member accelerations
     */
    FASTDDS_EXPORTED_API void accelerations(
            const std::vector<double>& _accelerations);

    /*!
     * @brief This function moves the value in member accelerations
     * @param _accelerations New value to be moved in member accelerations
     */
    FASTDDS_EXPORTED_API void accelerations(
            std::vector<double>&& _accelerations);

    /*!
     * @brief This function returns a constant reference to member accelerations
     * @return Constant reference to member accelerations
     */
    FASTDDS_EXPORTED_API const std::vector<double>& accelerations() const;

    /*!
     * @brief This function returns a reference to member accelerations
     * @return Reference to member accelerations
     */
    FASTDDS_EXPORTED_API std::vector<double>& accelerations();


    /*!
     * @brief This function copies the value in member effort
     * @param _effort New value to be copied in member effort
     */
    FASTDDS_EXPORTED_API void effort(
            const std::vector<double>& _effort);

    /*!
     * @brief This function moves the value in member effort
     * @param _effort New value to be moved in member effort
     */
    FASTDDS_EXPORTED_API void effort(
            std::vector<double>&& _effort);

    /*!
     * @brief This function returns a constant reference to member effort
     * @return Constant reference to member effort
     */
    FASTDDS_EXPORTED_API const std::vector<double>& effort() const;

    /*!
     * @brief This function returns a reference to member effort
     * @return Reference to member effort
     */
    FASTDDS_EXPORTED_API std::vector<double>& effort();


    /*!
     * @brief This function copies the value in member time_from_start
     * @param _time_from_start New value to be copied in member time_from_start
     */
    FASTDDS_EXPORTED_API void time_from_start(
            const builtin_interfaces::msg::Duration& _time_from_start);

    /*!
     * @brief This function moves the value in member time_from_start
     * @param _time_from_start New value to be moved in member time_from_start
     */
    FASTDDS_EXPORTED_API void time_from_start(
            builtin_interfaces::msg::Duration&& _time_from_start);

    /*!
     * @brief This function returns a constant reference to member time_from_start
     * @return Constant reference to member time_from_start
     */
    FASTDDS_EXPORTED_API const builtin_interfaces::msg::Duration& time_from_start() const;

    /*!
     * @brief This function returns a reference to member time_from_start
     * @return Reference to member time_from_start
     */
    FASTDDS_EXPORTED_API builtin_interfaces::msg::Duration& time_from_start();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    std::vector<double> m_positions;
    std::vector<double> m_velocities;
    std::vector<double> m_accelerations;
    std::vector<double> m_effort;
    builtin_interfaces::msg::Duration m_time_from_start;

};

} // namespace msg

} // namespace trajectory_msgs

#endif // _FAST_DDS_GENERATED_TRAJECTORY_MSGS_MSG_JOINTTRAJECTORYPOINT_H_



