// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Joy.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_JOY_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_JOY_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "Header.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(JOY_SOURCE)
#define JOY_DllAPI __declspec( dllexport )
#else
#define JOY_DllAPI __declspec( dllimport )
#endif // JOY_SOURCE
#else
#define JOY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define JOY_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace sensor_msgs {

namespace msg {





/*!
 * @brief This class represents the structure Joy defined by the user in the IDL file.
 * @ingroup Joy
 */
class Joy : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef Joy type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API Joy();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~Joy() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object sensor_msgs::msg::Joy that will be copied.
     */
    FASTDDS_EXPORTED_API Joy(
            const Joy& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object sensor_msgs::msg::Joy that will be copied.
     */
    FASTDDS_EXPORTED_API Joy(
            Joy&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object sensor_msgs::msg::Joy that will be copied.
     */
    FASTDDS_EXPORTED_API Joy& operator =(
            const Joy& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object sensor_msgs::msg::Joy that will be copied.
     */
    FASTDDS_EXPORTED_API Joy& operator =(
            Joy&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::Joy object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const Joy& x) const;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::Joy object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const Joy& x) const;

    /*!
     * @brief This function copies the value in member header_
     * @param _header_ New value to be copied in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            const std_msgs::msg::Header& _header_);

    /*!
     * @brief This function moves the value in member header_
     * @param _header_ New value to be moved in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            std_msgs::msg::Header&& _header_);

    /*!
     * @brief This function returns a constant reference to member header_
     * @return Constant reference to member header_
     */
    FASTDDS_EXPORTED_API const std_msgs::msg::Header& header_() const;

    /*!
     * @brief This function returns a reference to member header_
     * @return Reference to member header_
     */
    FASTDDS_EXPORTED_API std_msgs::msg::Header& header_();


    /*!
     * @brief This function copies the value in member axes
     * @param _axes New value to be copied in member axes
     */
    FASTDDS_EXPORTED_API void axes(
            const std::vector<float>& _axes);

    /*!
     * @brief This function moves the value in member axes
     * @param _axes New value to be moved in member axes
     */
    FASTDDS_EXPORTED_API void axes(
            std::vector<float>&& _axes);

    /*!
     * @brief This function returns a constant reference to member axes
     * @return Constant reference to member axes
     */
    FASTDDS_EXPORTED_API const std::vector<float>& axes() const;

    /*!
     * @brief This function returns a reference to member axes
     * @return Reference to member axes
     */
    FASTDDS_EXPORTED_API std::vector<float>& axes();


    /*!
     * @brief This function copies the value in member buttons
     * @param _buttons New value to be copied in member buttons
     */
    FASTDDS_EXPORTED_API void buttons(
            const std::vector<int32_t>& _buttons);

    /*!
     * @brief This function moves the value in member buttons
     * @param _buttons New value to be moved in member buttons
     */
    FASTDDS_EXPORTED_API void buttons(
            std::vector<int32_t>&& _buttons);

    /*!
     * @brief This function returns a constant reference to member buttons
     * @return Constant reference to member buttons
     */
    FASTDDS_EXPORTED_API const std::vector<int32_t>& buttons() const;

    /*!
     * @brief This function returns a reference to member buttons
     * @return Reference to member buttons
     */
    FASTDDS_EXPORTED_API std::vector<int32_t>& buttons();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    std_msgs::msg::Header m_header_;
    std::vector<float> m_axes;
    std::vector<int32_t> m_buttons;

};

} // namespace msg

} // namespace sensor_msgs

#endif // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_JOY_H_



