// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MotorCommand.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_ROBOT_MSGS_MOTORCOMMAND_H_
#define _FAST_DDS_GENERATED_ROBOT_MSGS_MOTORCOMMAND_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MOTORCOMMAND_SOURCE)
#define MOTORCOMMAND_DllAPI __declspec( dllexport )
#else
#define MOTORCOMMAND_DllAPI __declspec( dllimport )
#endif // MOTORCOMMAND_SOURCE
#else
#define MOTORCOMMAND_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MOTORCOMMAND_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace robot_msgs {



/*!
 * @brief This class represents the structure MotorCommand defined by the user in the IDL file.
 * @ingroup MotorCommand
 */
class MotorCommand : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef MotorCommand type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API MotorCommand();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~MotorCommand() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object robot_msgs::MotorCommand that will be copied.
     */
    FASTDDS_EXPORTED_API MotorCommand(
            const MotorCommand& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object robot_msgs::MotorCommand that will be copied.
     */
    FASTDDS_EXPORTED_API MotorCommand(
            MotorCommand&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object robot_msgs::MotorCommand that will be copied.
     */
    FASTDDS_EXPORTED_API MotorCommand& operator =(
            const MotorCommand& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object robot_msgs::MotorCommand that will be copied.
     */
    FASTDDS_EXPORTED_API MotorCommand& operator =(
            MotorCommand&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x robot_msgs::MotorCommand object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const MotorCommand& x) const;

    /*!
     * @brief Comparison operator.
     * @param x robot_msgs::MotorCommand object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const MotorCommand& x) const;

    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    FASTDDS_EXPORTED_API void id(
            uint32_t _id);

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    FASTDDS_EXPORTED_API uint32_t id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    FASTDDS_EXPORTED_API uint32_t& id();


    /*!
     * @brief This function sets a value in member position
     * @param _position New value for member position
     */
    FASTDDS_EXPORTED_API void position(
            double _position);

    /*!
     * @brief This function returns the value of member position
     * @return Value of member position
     */
    FASTDDS_EXPORTED_API double position() const;

    /*!
     * @brief This function returns a reference to member position
     * @return Reference to member position
     */
    FASTDDS_EXPORTED_API double& position();


    /*!
     * @brief This function sets a value in member velocity
     * @param _velocity New value for member velocity
     */
    FASTDDS_EXPORTED_API void velocity(
            double _velocity);

    /*!
     * @brief This function returns the value of member velocity
     * @return Value of member velocity
     */
    FASTDDS_EXPORTED_API double velocity() const;

    /*!
     * @brief This function returns a reference to member velocity
     * @return Reference to member velocity
     */
    FASTDDS_EXPORTED_API double& velocity();


    /*!
     * @brief This function sets a value in member torque
     * @param _torque New value for member torque
     */
    FASTDDS_EXPORTED_API void torque(
            double _torque);

    /*!
     * @brief This function returns the value of member torque
     * @return Value of member torque
     */
    FASTDDS_EXPORTED_API double torque() const;

    /*!
     * @brief This function returns a reference to member torque
     * @return Reference to member torque
     */
    FASTDDS_EXPORTED_API double& torque();


    /*!
     * @brief This function sets a value in member kp
     * @param _kp New value for member kp
     */
    FASTDDS_EXPORTED_API void kp(
            double _kp);

    /*!
     * @brief This function returns the value of member kp
     * @return Value of member kp
     */
    FASTDDS_EXPORTED_API double kp() const;

    /*!
     * @brief This function returns a reference to member kp
     * @return Reference to member kp
     */
    FASTDDS_EXPORTED_API double& kp();


    /*!
     * @brief This function sets a value in member kd
     * @param _kd New value for member kd
     */
    FASTDDS_EXPORTED_API void kd(
            double _kd);

    /*!
     * @brief This function returns the value of member kd
     * @return Value of member kd
     */
    FASTDDS_EXPORTED_API double kd() const;

    /*!
     * @brief This function returns a reference to member kd
     * @return Reference to member kd
     */
    FASTDDS_EXPORTED_API double& kd();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    uint32_t m_id{0};
    double m_position{0.0};
    double m_velocity{0.0};
    double m_torque{0.0};
    double m_kp{0.0};
    double m_kd{0.0};

};

} // namespace robot_msgs

#endif // _FAST_DDS_GENERATED_ROBOT_MSGS_MOTORCOMMAND_H_



