// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Path.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_NAV_MSGS_MSG_PATH_H_
#define _FAST_DDS_GENERATED_NAV_MSGS_MSG_PATH_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "PoseStamped.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(PATH_SOURCE)
#define PATH_DllAPI __declspec( dllexport )
#else
#define PATH_DllAPI __declspec( dllimport )
#endif // PATH_SOURCE
#else
#define PATH_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define PATH_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace nav_msgs {

namespace msg {





/*!
 * @brief This class represents the structure Path defined by the user in the IDL file.
 * @ingroup Path
 */
class Path : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef Path type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API Path();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~Path() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object nav_msgs::msg::Path that will be copied.
     */
    FASTDDS_EXPORTED_API Path(
            const Path& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object nav_msgs::msg::Path that will be copied.
     */
    FASTDDS_EXPORTED_API Path(
            Path&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object nav_msgs::msg::Path that will be copied.
     */
    FASTDDS_EXPORTED_API Path& operator =(
            const Path& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object nav_msgs::msg::Path that will be copied.
     */
    FASTDDS_EXPORTED_API Path& operator =(
            Path&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x nav_msgs::msg::Path object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const Path& x) const;

    /*!
     * @brief Comparison operator.
     * @param x nav_msgs::msg::Path object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const Path& x) const;

    /*!
     * @brief This function copies the value in member header_
     * @param _header_ New value to be copied in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            const std_msgs::msg::Header& _header_);

    /*!
     * @brief This function moves the value in member header_
     * @param _header_ New value to be moved in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            std_msgs::msg::Header&& _header_);

    /*!
     * @brief This function returns a constant reference to member header_
     * @return Constant reference to member header_
     */
    FASTDDS_EXPORTED_API const std_msgs::msg::Header& header_() const;

    /*!
     * @brief This function returns a reference to member header_
     * @return Reference to member header_
     */
    FASTDDS_EXPORTED_API std_msgs::msg::Header& header_();


    /*!
     * @brief This function copies the value in member poses
     * @param _poses New value to be copied in member poses
     */
    FASTDDS_EXPORTED_API void poses(
            const std::vector<geometry_msgs::msg::PoseStamped>& _poses);

    /*!
     * @brief This function moves the value in member poses
     * @param _poses New value to be moved in member poses
     */
    FASTDDS_EXPORTED_API void poses(
            std::vector<geometry_msgs::msg::PoseStamped>&& _poses);

    /*!
     * @brief This function returns a constant reference to member poses
     * @return Constant reference to member poses
     */
    FASTDDS_EXPORTED_API const std::vector<geometry_msgs::msg::PoseStamped>& poses() const;

    /*!
     * @brief This function returns a reference to member poses
     * @return Reference to member poses
     */
    FASTDDS_EXPORTED_API std::vector<geometry_msgs::msg::PoseStamped>& poses();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    std_msgs::msg::Header m_header_;
    std::vector<geometry_msgs::msg::PoseStamped> m_poses;

};

} // namespace msg

} // namespace nav_msgs

#endif // _FAST_DDS_GENERATED_NAV_MSGS_MSG_PATH_H_



