// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PointCloud2.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD2_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD2_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "Header.hpp"
#include "PointField.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(POINTCLOUD2_SOURCE)
#define POINTCLOUD2_DllAPI __declspec( dllexport )
#else
#define POINTCLOUD2_DllAPI __declspec( dllimport )
#endif // POINTCLOUD2_SOURCE
#else
#define POINTCLOUD2_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define POINTCLOUD2_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace sensor_msgs {

namespace msg {



/*!
 * @brief This class represents the structure PointCloud2 defined by the user in the IDL file.
 * @ingroup PointCloud2
 */
class PointCloud2 : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef PointCloud2 type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API PointCloud2();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~PointCloud2() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object sensor_msgs::msg::PointCloud2 that will be copied.
     */
    FASTDDS_EXPORTED_API PointCloud2(
            const PointCloud2& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object sensor_msgs::msg::PointCloud2 that will be copied.
     */
    FASTDDS_EXPORTED_API PointCloud2(
            PointCloud2&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object sensor_msgs::msg::PointCloud2 that will be copied.
     */
    FASTDDS_EXPORTED_API PointCloud2& operator =(
            const PointCloud2& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object sensor_msgs::msg::PointCloud2 that will be copied.
     */
    FASTDDS_EXPORTED_API PointCloud2& operator =(
            PointCloud2&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::PointCloud2 object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const PointCloud2& x) const;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::PointCloud2 object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const PointCloud2& x) const;

    /*!
     * @brief This function copies the value in member header_
     * @param _header_ New value to be copied in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            const std_msgs::msg::Header& _header_);

    /*!
     * @brief This function moves the value in member header_
     * @param _header_ New value to be moved in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            std_msgs::msg::Header&& _header_);

    /*!
     * @brief This function returns a constant reference to member header_
     * @return Constant reference to member header_
     */
    FASTDDS_EXPORTED_API const std_msgs::msg::Header& header_() const;

    /*!
     * @brief This function returns a reference to member header_
     * @return Reference to member header_
     */
    FASTDDS_EXPORTED_API std_msgs::msg::Header& header_();


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    FASTDDS_EXPORTED_API void height(
            uint32_t _height);

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    FASTDDS_EXPORTED_API uint32_t height() const;

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    FASTDDS_EXPORTED_API uint32_t& height();


    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    FASTDDS_EXPORTED_API void width(
            uint32_t _width);

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    FASTDDS_EXPORTED_API uint32_t width() const;

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    FASTDDS_EXPORTED_API uint32_t& width();


    /*!
     * @brief This function copies the value in member fields
     * @param _fields New value to be copied in member fields
     */
    FASTDDS_EXPORTED_API void fields(
            const std::vector<sensor_msgs::msg::PointField>& _fields);

    /*!
     * @brief This function moves the value in member fields
     * @param _fields New value to be moved in member fields
     */
    FASTDDS_EXPORTED_API void fields(
            std::vector<sensor_msgs::msg::PointField>&& _fields);

    /*!
     * @brief This function returns a constant reference to member fields
     * @return Constant reference to member fields
     */
    FASTDDS_EXPORTED_API const std::vector<sensor_msgs::msg::PointField>& fields() const;

    /*!
     * @brief This function returns a reference to member fields
     * @return Reference to member fields
     */
    FASTDDS_EXPORTED_API std::vector<sensor_msgs::msg::PointField>& fields();


    /*!
     * @brief This function sets a value in member is_bigendian
     * @param _is_bigendian New value for member is_bigendian
     */
    FASTDDS_EXPORTED_API void is_bigendian(
            bool _is_bigendian);

    /*!
     * @brief This function returns the value of member is_bigendian
     * @return Value of member is_bigendian
     */
    FASTDDS_EXPORTED_API bool is_bigendian() const;

    /*!
     * @brief This function returns a reference to member is_bigendian
     * @return Reference to member is_bigendian
     */
    FASTDDS_EXPORTED_API bool& is_bigendian();


    /*!
     * @brief This function sets a value in member point_step
     * @param _point_step New value for member point_step
     */
    FASTDDS_EXPORTED_API void point_step(
            uint32_t _point_step);

    /*!
     * @brief This function returns the value of member point_step
     * @return Value of member point_step
     */
    FASTDDS_EXPORTED_API uint32_t point_step() const;

    /*!
     * @brief This function returns a reference to member point_step
     * @return Reference to member point_step
     */
    FASTDDS_EXPORTED_API uint32_t& point_step();


    /*!
     * @brief This function sets a value in member row_step
     * @param _row_step New value for member row_step
     */
    FASTDDS_EXPORTED_API void row_step(
            uint32_t _row_step);

    /*!
     * @brief This function returns the value of member row_step
     * @return Value of member row_step
     */
    FASTDDS_EXPORTED_API uint32_t row_step() const;

    /*!
     * @brief This function returns a reference to member row_step
     * @return Reference to member row_step
     */
    FASTDDS_EXPORTED_API uint32_t& row_step();


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    FASTDDS_EXPORTED_API void data(
            const std::vector<uint8_t>& _data);

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    FASTDDS_EXPORTED_API void data(
            std::vector<uint8_t>&& _data);

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    FASTDDS_EXPORTED_API const std::vector<uint8_t>& data() const;

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    FASTDDS_EXPORTED_API std::vector<uint8_t>& data();


    /*!
     * @brief This function sets a value in member is_dense
     * @param _is_dense New value for member is_dense
     */
    FASTDDS_EXPORTED_API void is_dense(
            bool _is_dense);

    /*!
     * @brief This function returns the value of member is_dense
     * @return Value of member is_dense
     */
    FASTDDS_EXPORTED_API bool is_dense() const;

    /*!
     * @brief This function returns a reference to member is_dense
     * @return Reference to member is_dense
     */
    FASTDDS_EXPORTED_API bool& is_dense();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    std_msgs::msg::Header m_header_;
    uint32_t m_height{0};
    uint32_t m_width{0};
    std::vector<sensor_msgs::msg::PointField> m_fields;
    bool m_is_bigendian{false};
    uint32_t m_point_step{0};
    uint32_t m_row_step{0};
    std::vector<uint8_t> m_data;
    bool m_is_dense{false};

};

} // namespace msg

} // namespace sensor_msgs

#endif // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD2_H_



