// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Point32.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_POINT32_H_
#define _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_POINT32_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(POINT32_SOURCE)
#define POINT32_DllAPI __declspec( dllexport )
#else
#define POINT32_DllAPI __declspec( dllimport )
#endif // POINT32_SOURCE
#else
#define POINT32_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define POINT32_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace geometry_msgs {

namespace msg {



/*!
 * @brief This class represents the structure Point32 defined by the user in the IDL file.
 * @ingroup Point32
 */
class Point32 : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef Point32 type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API Point32();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~Point32() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object geometry_msgs::msg::Point32 that will be copied.
     */
    FASTDDS_EXPORTED_API Point32(
            const Point32& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object geometry_msgs::msg::Point32 that will be copied.
     */
    FASTDDS_EXPORTED_API Point32(
            Point32&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object geometry_msgs::msg::Point32 that will be copied.
     */
    FASTDDS_EXPORTED_API Point32& operator =(
            const Point32& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object geometry_msgs::msg::Point32 that will be copied.
     */
    FASTDDS_EXPORTED_API Point32& operator =(
            Point32&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x geometry_msgs::msg::Point32 object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const Point32& x) const;

    /*!
     * @brief Comparison operator.
     * @param x geometry_msgs::msg::Point32 object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const Point32& x) const;

    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    FASTDDS_EXPORTED_API void x(
            float _x);

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    FASTDDS_EXPORTED_API float x() const;

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    FASTDDS_EXPORTED_API float& x();


    /*!
     * @brief This function sets a value in member y
     * @param _y New value for member y
     */
    FASTDDS_EXPORTED_API void y(
            float _y);

    /*!
     * @brief This function returns the value of member y
     * @return Value of member y
     */
    FASTDDS_EXPORTED_API float y() const;

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    FASTDDS_EXPORTED_API float& y();


    /*!
     * @brief This function sets a value in member z
     * @param _z New value for member z
     */
    FASTDDS_EXPORTED_API void z(
            float _z);

    /*!
     * @brief This function returns the value of member z
     * @return Value of member z
     */
    FASTDDS_EXPORTED_API float z() const;

    /*!
     * @brief This function returns a reference to member z
     * @return Reference to member z
     */
    FASTDDS_EXPORTED_API float& z();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    float m_x{0.0};
    float m_y{0.0};
    float m_z{0.0};

};

} // namespace msg

} // namespace geometry_msgs

#endif // _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_POINT32_H_



