// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Range.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_RANGE_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_RANGE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "Header.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(RANGE_SOURCE)
#define RANGE_DllAPI __declspec( dllexport )
#else
#define RANGE_DllAPI __declspec( dllimport )
#endif // RANGE_SOURCE
#else
#define RANGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define RANGE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace sensor_msgs {

namespace msg {

namespace Range_Constants {

const uint8_t ULTRASOUND = 0;
const uint8_t INFRARED = 1;

} // namespace Range_Constants


/*!
 * @brief This class represents the structure Range defined by the user in the IDL file.
 * @ingroup Range
 */
class Range : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef Range type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API Range();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~Range() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object sensor_msgs::msg::Range that will be copied.
     */
    FASTDDS_EXPORTED_API Range(
            const Range& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object sensor_msgs::msg::Range that will be copied.
     */
    FASTDDS_EXPORTED_API Range(
            Range&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object sensor_msgs::msg::Range that will be copied.
     */
    FASTDDS_EXPORTED_API Range& operator =(
            const Range& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object sensor_msgs::msg::Range that will be copied.
     */
    FASTDDS_EXPORTED_API Range& operator =(
            Range&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::Range object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const Range& x) const;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::Range object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const Range& x) const;

    /*!
     * @brief This function copies the value in member header_
     * @param _header_ New value to be copied in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            const std_msgs::msg::Header& _header_);

    /*!
     * @brief This function moves the value in member header_
     * @param _header_ New value to be moved in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            std_msgs::msg::Header&& _header_);

    /*!
     * @brief This function returns a constant reference to member header_
     * @return Constant reference to member header_
     */
    FASTDDS_EXPORTED_API const std_msgs::msg::Header& header_() const;

    /*!
     * @brief This function returns a reference to member header_
     * @return Reference to member header_
     */
    FASTDDS_EXPORTED_API std_msgs::msg::Header& header_();


    /*!
     * @brief This function sets a value in member radiation_type
     * @param _radiation_type New value for member radiation_type
     */
    FASTDDS_EXPORTED_API void radiation_type(
            uint8_t _radiation_type);

    /*!
     * @brief This function returns the value of member radiation_type
     * @return Value of member radiation_type
     */
    FASTDDS_EXPORTED_API uint8_t radiation_type() const;

    /*!
     * @brief This function returns a reference to member radiation_type
     * @return Reference to member radiation_type
     */
    FASTDDS_EXPORTED_API uint8_t& radiation_type();


    /*!
     * @brief This function sets a value in member field_of_view
     * @param _field_of_view New value for member field_of_view
     */
    FASTDDS_EXPORTED_API void field_of_view(
            float _field_of_view);

    /*!
     * @brief This function returns the value of member field_of_view
     * @return Value of member field_of_view
     */
    FASTDDS_EXPORTED_API float field_of_view() const;

    /*!
     * @brief This function returns a reference to member field_of_view
     * @return Reference to member field_of_view
     */
    FASTDDS_EXPORTED_API float& field_of_view();


    /*!
     * @brief This function sets a value in member min_range
     * @param _min_range New value for member min_range
     */
    FASTDDS_EXPORTED_API void min_range(
            float _min_range);

    /*!
     * @brief This function returns the value of member min_range
     * @return Value of member min_range
     */
    FASTDDS_EXPORTED_API float min_range() const;

    /*!
     * @brief This function returns a reference to member min_range
     * @return Reference to member min_range
     */
    FASTDDS_EXPORTED_API float& min_range();


    /*!
     * @brief This function sets a value in member max_range
     * @param _max_range New value for member max_range
     */
    FASTDDS_EXPORTED_API void max_range(
            float _max_range);

    /*!
     * @brief This function returns the value of member max_range
     * @return Value of member max_range
     */
    FASTDDS_EXPORTED_API float max_range() const;

    /*!
     * @brief This function returns a reference to member max_range
     * @return Reference to member max_range
     */
    FASTDDS_EXPORTED_API float& max_range();


    /*!
     * @brief This function sets a value in member range
     * @param _range New value for member range
     */
    FASTDDS_EXPORTED_API void range(
            float _range);

    /*!
     * @brief This function returns the value of member range
     * @return Value of member range
     */
    FASTDDS_EXPORTED_API float range() const;

    /*!
     * @brief This function returns a reference to member range
     * @return Reference to member range
     */
    FASTDDS_EXPORTED_API float& range();


    /*!
     * @brief This function sets a value in member variance
     * @param _variance New value for member variance
     */
    FASTDDS_EXPORTED_API void variance(
            float _variance);

    /*!
     * @brief This function returns the value of member variance
     * @return Value of member variance
     */
    FASTDDS_EXPORTED_API float variance() const;

    /*!
     * @brief This function returns a reference to member variance
     * @return Reference to member variance
     */
    FASTDDS_EXPORTED_API float& variance();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    std_msgs::msg::Header m_header_;
    uint8_t m_radiation_type{0};
    float m_field_of_view{0.0};
    float m_min_range{0.0};
    float m_max_range{0.0};
    float m_range{0.0};
    float m_variance{0.0};

};

} // namespace msg

} // namespace sensor_msgs

#endif // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_RANGE_H_



