// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RelativeHumidity.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_RELATIVEHUMIDITY_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_RELATIVEHUMIDITY_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "Header.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(RELATIVEHUMIDITY_SOURCE)
#define RELATIVEHUMIDITY_DllAPI __declspec( dllexport )
#else
#define RELATIVEHUMIDITY_DllAPI __declspec( dllimport )
#endif // RELATIVEHUMIDITY_SOURCE
#else
#define RELATIVEHUMIDITY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define RELATIVEHUMIDITY_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace sensor_msgs {

namespace msg {



/*!
 * @brief This class represents the structure RelativeHumidity defined by the user in the IDL file.
 * @ingroup RelativeHumidity
 */
class RelativeHumidity : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef RelativeHumidity type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API RelativeHumidity();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~RelativeHumidity() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object sensor_msgs::msg::RelativeHumidity that will be copied.
     */
    FASTDDS_EXPORTED_API RelativeHumidity(
            const RelativeHumidity& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object sensor_msgs::msg::RelativeHumidity that will be copied.
     */
    FASTDDS_EXPORTED_API RelativeHumidity(
            RelativeHumidity&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object sensor_msgs::msg::RelativeHumidity that will be copied.
     */
    FASTDDS_EXPORTED_API RelativeHumidity& operator =(
            const RelativeHumidity& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object sensor_msgs::msg::RelativeHumidity that will be copied.
     */
    FASTDDS_EXPORTED_API RelativeHumidity& operator =(
            RelativeHumidity&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::RelativeHumidity object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const RelativeHumidity& x) const;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::RelativeHumidity object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const RelativeHumidity& x) const;

    /*!
     * @brief This function copies the value in member header_
     * @param _header_ New value to be copied in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            const std_msgs::msg::Header& _header_);

    /*!
     * @brief This function moves the value in member header_
     * @param _header_ New value to be moved in member header_
     */
    FASTDDS_EXPORTED_API void header_(
            std_msgs::msg::Header&& _header_);

    /*!
     * @brief This function returns a constant reference to member header_
     * @return Constant reference to member header_
     */
    FASTDDS_EXPORTED_API const std_msgs::msg::Header& header_() const;

    /*!
     * @brief This function returns a reference to member header_
     * @return Reference to member header_
     */
    FASTDDS_EXPORTED_API std_msgs::msg::Header& header_();


    /*!
     * @brief This function sets a value in member relative_humidity
     * @param _relative_humidity New value for member relative_humidity
     */
    FASTDDS_EXPORTED_API void relative_humidity(
            double _relative_humidity);

    /*!
     * @brief This function returns the value of member relative_humidity
     * @return Value of member relative_humidity
     */
    FASTDDS_EXPORTED_API double relative_humidity() const;

    /*!
     * @brief This function returns a reference to member relative_humidity
     * @return Reference to member relative_humidity
     */
    FASTDDS_EXPORTED_API double& relative_humidity();


    /*!
     * @brief This function sets a value in member variance
     * @param _variance New value for member variance
     */
    FASTDDS_EXPORTED_API void variance(
            double _variance);

    /*!
     * @brief This function returns the value of member variance
     * @return Value of member variance
     */
    FASTDDS_EXPORTED_API double variance() const;

    /*!
     * @brief This function returns a reference to member variance
     * @return Reference to member variance
     */
    FASTDDS_EXPORTED_API double& variance();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    std_msgs::msg::Header m_header_;
    double m_relative_humidity{0.0};
    double m_variance{0.0};

};

} // namespace msg

} // namespace sensor_msgs

#endif // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_RELATIVEHUMIDITY_H_



