// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RpcReqMsg.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_JSR_MSG_RPCREQMSG_H_
#define _FAST_DDS_GENERATED_JSR_MSG_RPCREQMSG_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(RPCREQMSG_SOURCE)
#define RPCREQMSG_DllAPI __declspec( dllexport )
#else
#define RPCREQMSG_DllAPI __declspec( dllimport )
#endif // RPCREQMSG_SOURCE
#else
#define RPCREQMSG_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define RPCREQMSG_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace jsr {

namespace msg {



/*!
 * @brief This class represents the structure RpcReqMsg defined by the user in the IDL file.
 * @ingroup RpcReqMsg
 */
class RpcReqMsg : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef RpcReqMsg type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API RpcReqMsg();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~RpcReqMsg() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object jsr::msg::RpcReqMsg that will be copied.
     */
    FASTDDS_EXPORTED_API RpcReqMsg(
            const RpcReqMsg& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object jsr::msg::RpcReqMsg that will be copied.
     */
    FASTDDS_EXPORTED_API RpcReqMsg(
            RpcReqMsg&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object jsr::msg::RpcReqMsg that will be copied.
     */
    FASTDDS_EXPORTED_API RpcReqMsg& operator =(
            const RpcReqMsg& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object jsr::msg::RpcReqMsg that will be copied.
     */
    FASTDDS_EXPORTED_API RpcReqMsg& operator =(
            RpcReqMsg&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::RpcReqMsg object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const RpcReqMsg& x) const;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::RpcReqMsg object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const RpcReqMsg& x) const;

    /*!
     * @brief This function sets a value in member uuid
     * @param _uuid New value for member uuid
     */
    FASTDDS_EXPORTED_API void uuid(
            uint64_t _uuid);

    /*!
     * @brief This function returns the value of member uuid
     * @return Value of member uuid
     */
    FASTDDS_EXPORTED_API uint64_t uuid() const;

    /*!
     * @brief This function returns a reference to member uuid
     * @return Reference to member uuid
     */
    FASTDDS_EXPORTED_API uint64_t& uuid();


    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    FASTDDS_EXPORTED_API void header(
            const std::string& _header);

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    FASTDDS_EXPORTED_API void header(
            std::string&& _header);

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    FASTDDS_EXPORTED_API const std::string& header() const;

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    FASTDDS_EXPORTED_API std::string& header();


    /*!
     * @brief This function copies the value in member body
     * @param _body New value to be copied in member body
     */
    FASTDDS_EXPORTED_API void body(
            const std::string& _body);

    /*!
     * @brief This function moves the value in member body
     * @param _body New value to be moved in member body
     */
    FASTDDS_EXPORTED_API void body(
            std::string&& _body);

    /*!
     * @brief This function returns a constant reference to member body
     * @return Constant reference to member body
     */
    FASTDDS_EXPORTED_API const std::string& body() const;

    /*!
     * @brief This function returns a reference to member body
     * @return Reference to member body
     */
    FASTDDS_EXPORTED_API std::string& body();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    uint64_t m_uuid{0};
    std::string m_header;
    std::string m_body;

};

} // namespace msg

} // namespace jsr

#endif // _FAST_DDS_GENERATED_JSR_MSG_RPCREQMSG_H_



