// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Time.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_BUILTIN_INTERFACES_MSG_TIME_H_
#define _FAST_DDS_GENERATED_BUILTIN_INTERFACES_MSG_TIME_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TIME_SOURCE)
#define TIME_DllAPI __declspec( dllexport )
#else
#define TIME_DllAPI __declspec( dllimport )
#endif // TIME_SOURCE
#else
#define TIME_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TIME_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace builtin_interfaces {

namespace msg {



/*!
 * @brief This class represents the structure Time defined by the user in the IDL file.
 * @ingroup Time
 */
class Time : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef Time type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API Time();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~Time() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object builtin_interfaces::msg::Time that will be copied.
     */
    FASTDDS_EXPORTED_API Time(
            const Time& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object builtin_interfaces::msg::Time that will be copied.
     */
    FASTDDS_EXPORTED_API Time(
            Time&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object builtin_interfaces::msg::Time that will be copied.
     */
    FASTDDS_EXPORTED_API Time& operator =(
            const Time& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object builtin_interfaces::msg::Time that will be copied.
     */
    FASTDDS_EXPORTED_API Time& operator =(
            Time&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x builtin_interfaces::msg::Time object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const Time& x) const;

    /*!
     * @brief Comparison operator.
     * @param x builtin_interfaces::msg::Time object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const Time& x) const;

    /*!
     * @brief This function sets a value in member sec
     * @param _sec New value for member sec
     */
    FASTDDS_EXPORTED_API void sec(
            int32_t _sec);

    /*!
     * @brief This function returns the value of member sec
     * @return Value of member sec
     */
    FASTDDS_EXPORTED_API int32_t sec() const;

    /*!
     * @brief This function returns a reference to member sec
     * @return Reference to member sec
     */
    FASTDDS_EXPORTED_API int32_t& sec();


    /*!
     * @brief This function sets a value in member nanosec
     * @param _nanosec New value for member nanosec
     */
    FASTDDS_EXPORTED_API void nanosec(
            uint32_t _nanosec);

    /*!
     * @brief This function returns the value of member nanosec
     * @return Value of member nanosec
     */
    FASTDDS_EXPORTED_API uint32_t nanosec() const;

    /*!
     * @brief This function returns a reference to member nanosec
     * @return Reference to member nanosec
     */
    FASTDDS_EXPORTED_API uint32_t& nanosec();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    int32_t m_sec{0};
    uint32_t m_nanosec{0};

};

} // namespace msg

} // namespace builtin_interfaces

#endif // _FAST_DDS_GENERATED_BUILTIN_INTERFACES_MSG_TIME_H_



