// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UVCoordinate.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_VISUALIZATION_MSGS_MSG_UVCOORDINATE_H_
#define _FAST_DDS_GENERATED_VISUALIZATION_MSGS_MSG_UVCOORDINATE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(UVCOORDINATE_SOURCE)
#define UVCOORDINATE_DllAPI __declspec( dllexport )
#else
#define UVCOORDINATE_DllAPI __declspec( dllimport )
#endif // UVCOORDINATE_SOURCE
#else
#define UVCOORDINATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define UVCOORDINATE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace visualization_msgs {

namespace msg {



/*!
 * @brief This class represents the structure UVCoordinate defined by the user in the IDL file.
 * @ingroup UVCoordinate
 */
class UVCoordinate : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef UVCoordinate type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API UVCoordinate();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~UVCoordinate() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object visualization_msgs::msg::UVCoordinate that will be copied.
     */
    FASTDDS_EXPORTED_API UVCoordinate(
            const UVCoordinate& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object visualization_msgs::msg::UVCoordinate that will be copied.
     */
    FASTDDS_EXPORTED_API UVCoordinate(
            UVCoordinate&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object visualization_msgs::msg::UVCoordinate that will be copied.
     */
    FASTDDS_EXPORTED_API UVCoordinate& operator =(
            const UVCoordinate& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object visualization_msgs::msg::UVCoordinate that will be copied.
     */
    FASTDDS_EXPORTED_API UVCoordinate& operator =(
            UVCoordinate&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x visualization_msgs::msg::UVCoordinate object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const UVCoordinate& x) const;

    /*!
     * @brief Comparison operator.
     * @param x visualization_msgs::msg::UVCoordinate object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const UVCoordinate& x) const;

    /*!
     * @brief This function sets a value in member u
     * @param _u New value for member u
     */
    FASTDDS_EXPORTED_API void u(
            float _u);

    /*!
     * @brief This function returns the value of member u
     * @return Value of member u
     */
    FASTDDS_EXPORTED_API float u() const;

    /*!
     * @brief This function returns a reference to member u
     * @return Reference to member u
     */
    FASTDDS_EXPORTED_API float& u();


    /*!
     * @brief This function sets a value in member v
     * @param _v New value for member v
     */
    FASTDDS_EXPORTED_API void v(
            float _v);

    /*!
     * @brief This function returns the value of member v
     * @return Value of member v
     */
    FASTDDS_EXPORTED_API float v() const;

    /*!
     * @brief This function returns a reference to member v
     * @return Reference to member v
     */
    FASTDDS_EXPORTED_API float& v();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    float m_u{0.0};
    float m_v{0.0};

};

} // namespace msg

} // namespace visualization_msgs

#endif // _FAST_DDS_GENERATED_VISUALIZATION_MSGS_MSG_UVCOORDINATE_H_



