// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BmsState.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_JSR_MSG_BMSSTATE_H_
#define _FAST_DDS_GENERATED_JSR_MSG_BMSSTATE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BMSSTATE_SOURCE)
#define BMSSTATE_DllAPI __declspec( dllexport )
#else
#define BMSSTATE_DllAPI __declspec( dllimport )
#endif // BMSSTATE_SOURCE
#else
#define BMSSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BMSSTATE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace jsr {

namespace msg {



/*!
 * @brief This class represents the structure BmsState defined by the user in the IDL file.
 * @ingroup BmsState
 */
class BmsState : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef BmsState type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API BmsState();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~BmsState() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object jsr::msg::BmsState that will be copied.
     */
    FASTDDS_EXPORTED_API BmsState(
            const BmsState& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object jsr::msg::BmsState that will be copied.
     */
    FASTDDS_EXPORTED_API BmsState(
            BmsState&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object jsr::msg::BmsState that will be copied.
     */
    FASTDDS_EXPORTED_API BmsState& operator =(
            const BmsState& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object jsr::msg::BmsState that will be copied.
     */
    FASTDDS_EXPORTED_API BmsState& operator =(
            BmsState&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::BmsState object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const BmsState& x) const;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::BmsState object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const BmsState& x) const;

    /*!
     * @brief This function sets a value in member voltage
     * @param _voltage New value for member voltage
     */
    FASTDDS_EXPORTED_API void voltage(
            float _voltage);

    /*!
     * @brief This function returns the value of member voltage
     * @return Value of member voltage
     */
    FASTDDS_EXPORTED_API float voltage() const;

    /*!
     * @brief This function returns a reference to member voltage
     * @return Reference to member voltage
     */
    FASTDDS_EXPORTED_API float& voltage();


    /*!
     * @brief This function sets a value in member current
     * @param _current New value for member current
     */
    FASTDDS_EXPORTED_API void current(
            float _current);

    /*!
     * @brief This function returns the value of member current
     * @return Value of member current
     */
    FASTDDS_EXPORTED_API float current() const;

    /*!
     * @brief This function returns a reference to member current
     * @return Reference to member current
     */
    FASTDDS_EXPORTED_API float& current();


    /*!
     * @brief This function sets a value in member remaining_cap
     * @param _remaining_cap New value for member remaining_cap
     */
    FASTDDS_EXPORTED_API void remaining_cap(
            float _remaining_cap);

    /*!
     * @brief This function returns the value of member remaining_cap
     * @return Value of member remaining_cap
     */
    FASTDDS_EXPORTED_API float remaining_cap() const;

    /*!
     * @brief This function returns a reference to member remaining_cap
     * @return Reference to member remaining_cap
     */
    FASTDDS_EXPORTED_API float& remaining_cap();


    /*!
     * @brief This function sets a value in member total_cap
     * @param _total_cap New value for member total_cap
     */
    FASTDDS_EXPORTED_API void total_cap(
            float _total_cap);

    /*!
     * @brief This function returns the value of member total_cap
     * @return Value of member total_cap
     */
    FASTDDS_EXPORTED_API float total_cap() const;

    /*!
     * @brief This function returns a reference to member total_cap
     * @return Reference to member total_cap
     */
    FASTDDS_EXPORTED_API float& total_cap();


    /*!
     * @brief This function sets a value in member soc
     * @param _soc New value for member soc
     */
    FASTDDS_EXPORTED_API void soc(
            float _soc);

    /*!
     * @brief This function returns the value of member soc
     * @return Value of member soc
     */
    FASTDDS_EXPORTED_API float soc() const;

    /*!
     * @brief This function returns a reference to member soc
     * @return Reference to member soc
     */
    FASTDDS_EXPORTED_API float& soc();


    /*!
     * @brief This function sets a value in member cycle
     * @param _cycle New value for member cycle
     */
    FASTDDS_EXPORTED_API void cycle(
            uint32_t _cycle);

    /*!
     * @brief This function returns the value of member cycle
     * @return Value of member cycle
     */
    FASTDDS_EXPORTED_API uint32_t cycle() const;

    /*!
     * @brief This function returns a reference to member cycle
     * @return Reference to member cycle
     */
    FASTDDS_EXPORTED_API uint32_t& cycle();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    float m_voltage{0.0};
    float m_current{0.0};
    float m_remaining_cap{0.0};
    float m_total_cap{0.0};
    float m_soc{0.0};
    uint32_t m_cycle{0};

};

} // namespace msg

} // namespace jsr

#endif // _FAST_DDS_GENERATED_JSR_MSG_BMSSTATE_H_



