// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ButtonEvent.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_JSR_MSG_BUTTONEVENT_H_
#define _FAST_DDS_GENERATED_JSR_MSG_BUTTONEVENT_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BUTTONEVENT_SOURCE)
#define BUTTONEVENT_DllAPI __declspec( dllexport )
#else
#define BUTTONEVENT_DllAPI __declspec( dllimport )
#endif // BUTTONEVENT_SOURCE
#else
#define BUTTONEVENT_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BUTTONEVENT_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace jsr {

namespace msg {

/*!
 * @brief This class represents the enumeration ButtonEventType defined by the user in the IDL file.
 * @ingroup ButtonEvent
 */
enum ButtonEventType : uint32_t
{
    PRESS_DOWN,
    PRESS_UP,
    SINGLE_CLICK,
    DOUBLE_CLICK,
    TRIPLE_CLICK,
    LONG_PRESS_START,
    LONG_PRESS_HOLD,
    LONG_PRESS_END
};


/*!
 * @brief This class represents the structure ButtonEventMsg defined by the user in the IDL file.
 * @ingroup ButtonEvent
 */
class ButtonEventMsg : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef ButtonEventMsg type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API ButtonEventMsg();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~ButtonEventMsg() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object jsr::msg::ButtonEventMsg that will be copied.
     */
    FASTDDS_EXPORTED_API ButtonEventMsg(
            const ButtonEventMsg& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object jsr::msg::ButtonEventMsg that will be copied.
     */
    FASTDDS_EXPORTED_API ButtonEventMsg(
            ButtonEventMsg&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object jsr::msg::ButtonEventMsg that will be copied.
     */
    FASTDDS_EXPORTED_API ButtonEventMsg& operator =(
            const ButtonEventMsg& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object jsr::msg::ButtonEventMsg that will be copied.
     */
    FASTDDS_EXPORTED_API ButtonEventMsg& operator =(
            ButtonEventMsg&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::ButtonEventMsg object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const ButtonEventMsg& x) const;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::ButtonEventMsg object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const ButtonEventMsg& x) const;

    /*!
     * @brief This function sets a value in member button
     * @param _button New value for member button
     */
    FASTDDS_EXPORTED_API void button(
            int32_t _button);

    /*!
     * @brief This function returns the value of member button
     * @return Value of member button
     */
    FASTDDS_EXPORTED_API int32_t button() const;

    /*!
     * @brief This function returns a reference to member button
     * @return Reference to member button
     */
    FASTDDS_EXPORTED_API int32_t& button();


    /*!
     * @brief This function sets a value in member event
     * @param _event New value for member event
     */
    FASTDDS_EXPORTED_API void event(
            jsr::msg::ButtonEventType _event);

    /*!
     * @brief This function returns the value of member event
     * @return Value of member event
     */
    FASTDDS_EXPORTED_API jsr::msg::ButtonEventType event() const;

    /*!
     * @brief This function returns a reference to member event
     * @return Reference to member event
     */
    FASTDDS_EXPORTED_API jsr::msg::ButtonEventType& event();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    int32_t m_button{0};
    jsr::msg::ButtonEventType m_event{jsr::msg::PRESS_DOWN};

};

} // namespace msg

} // namespace jsr

#endif // _FAST_DDS_GENERATED_JSR_MSG_BUTTONEVENT_H_



