// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LowCmd.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_JSR_MSG_LOWCMD_H_
#define _FAST_DDS_GENERATED_JSR_MSG_LOWCMD_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "MotorCmd.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LOWCMD_SOURCE)
#define LOWCMD_DllAPI __declspec( dllexport )
#else
#define LOWCMD_DllAPI __declspec( dllimport )
#endif // LOWCMD_SOURCE
#else
#define LOWCMD_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LOWCMD_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace jsr {

namespace msg {

/*!
 * @brief This class represents the enumeration CmdType defined by the user in the IDL file.
 * @ingroup LowCmd
 */
enum CmdType : uint32_t
{
    PARALLEL,
    SERIAL
};




/*!
 * @brief This class represents the structure LowCmd defined by the user in the IDL file.
 * @ingroup LowCmd
 */
class LowCmd : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef LowCmd type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API LowCmd();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~LowCmd() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object jsr::msg::LowCmd that will be copied.
     */
    FASTDDS_EXPORTED_API LowCmd(
            const LowCmd& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object jsr::msg::LowCmd that will be copied.
     */
    FASTDDS_EXPORTED_API LowCmd(
            LowCmd&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object jsr::msg::LowCmd that will be copied.
     */
    FASTDDS_EXPORTED_API LowCmd& operator =(
            const LowCmd& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object jsr::msg::LowCmd that will be copied.
     */
    FASTDDS_EXPORTED_API LowCmd& operator =(
            LowCmd&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::LowCmd object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const LowCmd& x) const;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::LowCmd object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const LowCmd& x) const;

    /*!
     * @brief This function sets a value in member cmd_type
     * @param _cmd_type New value for member cmd_type
     */
    FASTDDS_EXPORTED_API void cmd_type(
            jsr::msg::CmdType _cmd_type);

    /*!
     * @brief This function returns the value of member cmd_type
     * @return Value of member cmd_type
     */
    FASTDDS_EXPORTED_API jsr::msg::CmdType cmd_type() const;

    /*!
     * @brief This function returns a reference to member cmd_type
     * @return Reference to member cmd_type
     */
    FASTDDS_EXPORTED_API jsr::msg::CmdType& cmd_type();


    /*!
     * @brief This function copies the value in member motor_cmd
     * @param _motor_cmd New value to be copied in member motor_cmd
     */
    FASTDDS_EXPORTED_API void motor_cmd(
            const std::vector<jsr::msg::MotorCmd>& _motor_cmd);

    /*!
     * @brief This function moves the value in member motor_cmd
     * @param _motor_cmd New value to be moved in member motor_cmd
     */
    FASTDDS_EXPORTED_API void motor_cmd(
            std::vector<jsr::msg::MotorCmd>&& _motor_cmd);

    /*!
     * @brief This function returns a constant reference to member motor_cmd
     * @return Constant reference to member motor_cmd
     */
    FASTDDS_EXPORTED_API const std::vector<jsr::msg::MotorCmd>& motor_cmd() const;

    /*!
     * @brief This function returns a reference to member motor_cmd
     * @return Reference to member motor_cmd
     */
    FASTDDS_EXPORTED_API std::vector<jsr::msg::MotorCmd>& motor_cmd();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    jsr::msg::CmdType m_cmd_type{jsr::msg::PARALLEL};
    std::vector<jsr::msg::MotorCmd> m_motor_cmd;

};

} // namespace msg

} // namespace jsr

#endif // _FAST_DDS_GENERATED_JSR_MSG_LOWCMD_H_



