// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LowState.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_JSR_MSG_LOWSTATE_H_
#define _FAST_DDS_GENERATED_JSR_MSG_LOWSTATE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "BmsState.hpp"
#include "MotorState.hpp"
#include "ImuState.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LOWSTATE_SOURCE)
#define LOWSTATE_DllAPI __declspec( dllexport )
#else
#define LOWSTATE_DllAPI __declspec( dllimport )
#endif // LOWSTATE_SOURCE
#else
#define LOWSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LOWSTATE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace jsr {

namespace msg {





/*!
 * @brief This class represents the structure LowState defined by the user in the IDL file.
 * @ingroup LowState
 */
class LowState : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef LowState type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API LowState();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~LowState() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object jsr::msg::LowState that will be copied.
     */
    FASTDDS_EXPORTED_API LowState(
            const LowState& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object jsr::msg::LowState that will be copied.
     */
    FASTDDS_EXPORTED_API LowState(
            LowState&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object jsr::msg::LowState that will be copied.
     */
    FASTDDS_EXPORTED_API LowState& operator =(
            const LowState& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object jsr::msg::LowState that will be copied.
     */
    FASTDDS_EXPORTED_API LowState& operator =(
            LowState&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::LowState object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const LowState& x) const;

    /*!
     * @brief Comparison operator.
     * @param x jsr::msg::LowState object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const LowState& x) const;

    /*!
     * @brief This function copies the value in member bms_state
     * @param _bms_state New value to be copied in member bms_state
     */
    FASTDDS_EXPORTED_API void bms_state(
            const jsr::msg::BmsState& _bms_state);

    /*!
     * @brief This function moves the value in member bms_state
     * @param _bms_state New value to be moved in member bms_state
     */
    FASTDDS_EXPORTED_API void bms_state(
            jsr::msg::BmsState&& _bms_state);

    /*!
     * @brief This function returns a constant reference to member bms_state
     * @return Constant reference to member bms_state
     */
    FASTDDS_EXPORTED_API const jsr::msg::BmsState& bms_state() const;

    /*!
     * @brief This function returns a reference to member bms_state
     * @return Reference to member bms_state
     */
    FASTDDS_EXPORTED_API jsr::msg::BmsState& bms_state();


    /*!
     * @brief This function copies the value in member imu_state
     * @param _imu_state New value to be copied in member imu_state
     */
    FASTDDS_EXPORTED_API void imu_state(
            const jsr::msg::ImuState& _imu_state);

    /*!
     * @brief This function moves the value in member imu_state
     * @param _imu_state New value to be moved in member imu_state
     */
    FASTDDS_EXPORTED_API void imu_state(
            jsr::msg::ImuState&& _imu_state);

    /*!
     * @brief This function returns a constant reference to member imu_state
     * @return Constant reference to member imu_state
     */
    FASTDDS_EXPORTED_API const jsr::msg::ImuState& imu_state() const;

    /*!
     * @brief This function returns a reference to member imu_state
     * @return Reference to member imu_state
     */
    FASTDDS_EXPORTED_API jsr::msg::ImuState& imu_state();


    /*!
     * @brief This function copies the value in member motor_state_parallel
     * @param _motor_state_parallel New value to be copied in member motor_state_parallel
     */
    FASTDDS_EXPORTED_API void motor_state_parallel(
            const std::vector<jsr::msg::MotorState>& _motor_state_parallel);

    /*!
     * @brief This function moves the value in member motor_state_parallel
     * @param _motor_state_parallel New value to be moved in member motor_state_parallel
     */
    FASTDDS_EXPORTED_API void motor_state_parallel(
            std::vector<jsr::msg::MotorState>&& _motor_state_parallel);

    /*!
     * @brief This function returns a constant reference to member motor_state_parallel
     * @return Constant reference to member motor_state_parallel
     */
    FASTDDS_EXPORTED_API const std::vector<jsr::msg::MotorState>& motor_state_parallel() const;

    /*!
     * @brief This function returns a reference to member motor_state_parallel
     * @return Reference to member motor_state_parallel
     */
    FASTDDS_EXPORTED_API std::vector<jsr::msg::MotorState>& motor_state_parallel();


    /*!
     * @brief This function copies the value in member motor_state_serial
     * @param _motor_state_serial New value to be copied in member motor_state_serial
     */
    FASTDDS_EXPORTED_API void motor_state_serial(
            const std::vector<jsr::msg::MotorState>& _motor_state_serial);

    /*!
     * @brief This function moves the value in member motor_state_serial
     * @param _motor_state_serial New value to be moved in member motor_state_serial
     */
    FASTDDS_EXPORTED_API void motor_state_serial(
            std::vector<jsr::msg::MotorState>&& _motor_state_serial);

    /*!
     * @brief This function returns a constant reference to member motor_state_serial
     * @return Constant reference to member motor_state_serial
     */
    FASTDDS_EXPORTED_API const std::vector<jsr::msg::MotorState>& motor_state_serial() const;

    /*!
     * @brief This function returns a reference to member motor_state_serial
     * @return Reference to member motor_state_serial
     */
    FASTDDS_EXPORTED_API std::vector<jsr::msg::MotorState>& motor_state_serial();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    jsr::msg::BmsState m_bms_state;
    jsr::msg::ImuState m_imu_state;
    std::vector<jsr::msg::MotorState> m_motor_state_parallel;
    std::vector<jsr::msg::MotorState> m_motor_state_serial;

};

} // namespace msg

} // namespace jsr

#endif // _FAST_DDS_GENERATED_JSR_MSG_LOWSTATE_H_



