// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file union.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */


#ifndef _FAST_DDS_GENERATED_UNION_H_
#define _FAST_DDS_GENERATED_UNION_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>


#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define FASTDDS_EXPORTED_API __declspec( dllexport )
#else
#define FASTDDS_EXPORTED_API
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FASTDDS_EXPORTED_API
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(UNION_SOURCE)
#define UNION_DllAPI __declspec( dllexport )
#else
#define UNION_DllAPI __declspec( dllimport )
#endif // UNION_SOURCE
#else
#define UNION_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define UNION_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the union SensorUnion defined by the user in the IDL file.
 * @ingroup union
 */
class SensorUnion
{
public:

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API SensorUnion();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~SensorUnion();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SensorUnion that will be copied.
     */
    FASTDDS_EXPORTED_API SensorUnion(
            const SensorUnion& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SensorUnion that will be copied.
     */
    FASTDDS_EXPORTED_API SensorUnion(
            SensorUnion&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SensorUnion that will be copied.
     */
    FASTDDS_EXPORTED_API SensorUnion& operator =(
            const SensorUnion& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SensorUnion that will be copied.
     */
    FASTDDS_EXPORTED_API SensorUnion& operator =(
            SensorUnion&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x SensorUnion object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const SensorUnion& x) const;

    /*!
     * @brief Comparison operator.
     * @param x SensorUnion object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const SensorUnion& x) const;

    /*!
     * @brief This function sets the discriminator value.
     * @param __d New value for the discriminator.
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the new value doesn't correspond to the selected union member.
     */
    FASTDDS_EXPORTED_API void _d(
            uint8_t __d);

    /*!
     * @brief This function returns the value of the discriminator.
     * @return Value of the discriminator
     */
    FASTDDS_EXPORTED_API uint8_t _d() const;

    /*!
     * @brief This function returns a reference to the discriminator.
     * @return Reference to the discriminator.
     */
    FASTDDS_EXPORTED_API uint8_t& _d();

    /*!
     * @brief This function sets a value in member temperature
     * @param _temperature New value for member temperature
     */
    FASTDDS_EXPORTED_API void temperature(
            int8_t _temperature);

    /*!
     * @brief This function returns the value of member temperature
     * @return Value of member temperature
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    FASTDDS_EXPORTED_API int8_t temperature() const;

    /*!
     * @brief This function returns a reference to member temperature
     * @return Reference to member temperature
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    FASTDDS_EXPORTED_API int8_t& temperature();


    /*!
     * @brief This function sets a value in member voltage
     * @param _voltage New value for member voltage
     */
    FASTDDS_EXPORTED_API void voltage(
            float _voltage);

    /*!
     * @brief This function returns the value of member voltage
     * @return Value of member voltage
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    FASTDDS_EXPORTED_API float voltage() const;

    /*!
     * @brief This function returns a reference to member voltage
     * @return Reference to member voltage
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    FASTDDS_EXPORTED_API float& voltage();


    /*!
     * @brief This function sets a value in member power
     * @param _power New value for member power
     */
    FASTDDS_EXPORTED_API void power(
            int32_t _power);

    /*!
     * @brief This function returns the value of member power
     * @return Value of member power
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    FASTDDS_EXPORTED_API int32_t power() const;

    /*!
     * @brief This function returns a reference to member power
     * @return Reference to member power
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    FASTDDS_EXPORTED_API int32_t& power();

private:

    uint8_t m__d;

    int8_t m_temperature{0};
    float m_voltage{0.0};
    int32_t m_power{0};
};


/*!
 * @brief This class represents the structure Sensor defined by the user in the IDL file.
 * @ingroup union
 */
class Sensor : public eprosima::fastdds::dds::TopicDataType
{
public:

     typedef Sensor type;

    /*!
     * @brief Default constructor.
     */
    FASTDDS_EXPORTED_API Sensor();

    /*!
     * @brief Default destructor.
     */
    FASTDDS_EXPORTED_API ~Sensor() override;

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Sensor that will be copied.
     */
    FASTDDS_EXPORTED_API Sensor(
            const Sensor& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Sensor that will be copied.
     */
    FASTDDS_EXPORTED_API Sensor(
            Sensor&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Sensor that will be copied.
     */
    FASTDDS_EXPORTED_API Sensor& operator =(
            const Sensor& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Sensor that will be copied.
     */
    FASTDDS_EXPORTED_API Sensor& operator =(
            Sensor&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Sensor object to compare.
     */
    FASTDDS_EXPORTED_API bool operator ==(
            const Sensor& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Sensor object to compare.
     */
    FASTDDS_EXPORTED_API bool operator !=(
            const Sensor& x) const;

    /*!
     * @brief This function copies the value in member id
     * @param _id New value to be copied in member id
     */
    FASTDDS_EXPORTED_API void id(
            const std::string& _id);

    /*!
     * @brief This function moves the value in member id
     * @param _id New value to be moved in member id
     */
    FASTDDS_EXPORTED_API void id(
            std::string&& _id);

    /*!
     * @brief This function returns a constant reference to member id
     * @return Constant reference to member id
     */
    FASTDDS_EXPORTED_API const std::string& id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    FASTDDS_EXPORTED_API std::string& id();


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    FASTDDS_EXPORTED_API void data(
            const SensorUnion& _data);

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    FASTDDS_EXPORTED_API void data(
            SensorUnion&& _data);

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    FASTDDS_EXPORTED_API const SensorUnion& data() const;

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    FASTDDS_EXPORTED_API SensorUnion& data();


    FASTDDS_EXPORTED_API bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    FASTDDS_EXPORTED_API uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    FASTDDS_EXPORTED_API bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    FASTDDS_EXPORTED_API void* create_data() override;

    FASTDDS_EXPORTED_API void delete_data(
            void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    FASTDDS_EXPORTED_API inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    FASTDDS_EXPORTED_API inline bool is_plain(
        eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        static_cast<void>(data_representation);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    FASTDDS_EXPORTED_API inline bool construct_sample(
            void* memory) const override
    {
        static_cast<void>(memory);
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    eprosima::fastdds::MD5 m_md5;
    unsigned char* m_keyBuffer;



private:

    std::string m_id;
    SensorUnion m_data;

};

#endif // _FAST_DDS_GENERATED_UNION_H_



